---
title: "Untitled"
output: html_document
---

```{r}
#' Load useful packages
library(cluster)
library(dplyr)
library(ggplot2)
library(readr)
library(Rtsne)
```

```{r}
# read data and select age to do the clustering only for age, and separate it from numerical variable to categorical variable
data<-read.csv("bank.csv",sep=";")
df1<-data
df1$job<-factor(df1$job)
df1$marital<-factor(df1$marital)
df1$education<-factor(df1$education)
df1$default<-factor(df1$default)
df1$housing<-factor(df1$housing)
df1$loan<-factor(df1$loan)
df1$contact<-factor(df1$contact)
df1$month<-NULL
df1$poutcome<-factor(df1$poutcome)
df1$y<-factor(df1$y)
summary(df1)

df1<-df1[,c("balance","y")]
```




```{r}
#' Compute Gower distance
gower_dist <- daisy(df1, metric = "gower")
gower_mat <- as.matrix(gower_dist)
#' Print most similar clients
df1[which(gower_mat == min(gower_mat[gower_mat != min(gower_mat)]), arr.ind = TRUE)[1, ], ]

df1[which(gower_mat == max(gower_mat[gower_mat != max(gower_mat)]), arr.ind = TRUE)[1, ], ]


# find out the number of group to cluster balance to

sil_width <- c(NA)
for(i in 2:8){  
  pam_fit <- pam(gower_dist, diss = TRUE, k = i)  
  sil_width[i] <- pam_fit$silinfo$avg.width  
}
plot(1:8, sil_width,
     xlab = "Number of clusters",
     ylab = "Silhouette Width")
lines(1:8, sil_width)
```



```{r}
# clustering result of balance
k <- 5
pam_fit <- pam(gower_dist, diss = TRUE, k)
pam_results <- df1 %>%
  mutate(cluster = pam_fit$clustering) %>%
  group_by(cluster) %>%
  do(the_summary = summary(.))
pam_results$the_summary
```

```{r}
# visualization
tsne_obj <- Rtsne(gower_dist, is_distance = TRUE)
tsne_data <- tsne_obj$Y %>%
  data.frame() %>%
  setNames(c("X", "Y")) %>%
  mutate(cluster = factor(pam_fit$clustering))
ggplot(aes(x = X, y = Y), data = tsne_data) +
  geom_point(aes(color = cluster))
```